### ISSUE TITLE
Buck Bumble

### ISSUE THREAD

**Issue by bigbass1997** [Dillonb/n64#12]
Immediately crashes with invalid PIF command of `0xFD`. This seems similar to `0xFE` from Yoshi's Story https://github.com/Dillonb/n64/commit/a8dedc0b1b4fce74456f48a903ea15caefea66c0

For Yoshi's Story, Dillon had said that PIF RAM looked like this: `FF2301038001FEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEFEE121FE0A21FE0000000000000000000000000000000000000001`
@fraser125 decoded it so it's easier to understand:
```
FF - filler
23 - bytes sent in hex = 35 bytes
01 - 1 response byte
03 - read from controller pak 
8001 FEFEFEFE FEFEFEFE FEFEFEFE FEFEFEFE FEFEFEFE FEFEFEFE FEFEFEFE FEFEFEFE - where the read data will be placed
E1 - Response Byte
21 FE0A 21 - ???????????
FE - End of data
00000000 00000000 00000000 00000000 - Channel Skip and blank data
00000001 - PIF command 
```
So my guess is that perhaps there's a bug in how the emulator parses this memory for commands. Though I would be interested in seeing PIF RAM for Buck Bumble, and why it's parsing `0xFD`.

Log: https://gist.github.com/bigbass1997/3d9aa23246bfb39ee183587d304bd2d3

**Comment by Dillonb** [comment]
Thanks for the report! The PIF RAM contents when the game crashes are as follows:

`FDFDFDFDFE0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001`

If I skip every 0xFD and 0xFE byte, the game boots fine. I'll leave this issue open until we can figure out what hardware is supposed to do when given this data.

**Comment by Dillonb** [comment]
Looks like `FD` is a channel reset byte, and `FE` is a byte that signals the end of the PIF commands.

Closing the issue since the latest commits I've pushed resolve this.
