### ISSUE TITLE
Toy Story 2

### ISSUE THREAD

**Issue by bigbass1997** [Dillonb/n64#14]
Black/empty screen. Upon loading the ROM, the terminal begins being spammed with messages that it's trying to write data to an address `in unsupported region: REGION_CART_1_2`.

The messages continue until a fatal error occurs. When I redirected the output to a file, the file ended up being 3.1GB hehe. So the following log has the majority of these messages cut out. At some point fairly early (relatively), the word it's trying to write gets stuck at `0xB07F9C80` until the program crashes. The address always increments by 8 starting from `0x107F9C8C`, and crashes at `0x1FC00000`

Log: https://gist.github.com/bigbass1997/00dc33cfc1e44e8fde3636c3138a2e80

**Comment by Dillonb** [comment]
https://github.com/ares-emulator/ares/pull/529/files

Fix in Ares

**Comment by Dillonb** [comment]
Sorta fixed in https://github.com/Dillonb/n64/commit/a80c664c29a6d68dacda79b17c48563ee2e00e81. It gets to the main menu, but breaks with a black screen with music after trying to go in-game.

**Comment by Dillonb** [comment]
Fully fixed in https://github.com/Dillonb/n64/commit/9d48d5036cd7a0a32e092980bc5c2615b8fb274c
