### ISSUE TITLE
FrameBufferCPU Test Crash

### ISSUE THREAD

**Issue by bigbass1997** [Dillonb/n64#15]
Crash when running krom's test rom: https://github.com/PeterLemon/N64/tree/master/FrameBuffer/32BPP/FrameBufferCPU640x480

Based on the crash printout, I _think_ this is caused by not having the SYNC instruction implemented (or perhaps not just not being able to disassemble it). This instruction isn't typically in krom's CPU-based tests.

Log: https://gist.github.com/bigbass1997/9d0eda5c94e817730cce2297ec9f20e2

**Comment by Dillonb** [comment]
Yup, that was it. Thanks.

The `Disassembly Unsupported` message you got is because Capstone isn't installed on your system. Should work now, thanks again for the report :)
