### ISSUE TITLE
Super Mario 64 (Japan) - File select screen rendered incorrectly

### ISSUE THREAD

**Issue by HeroponRikiBestest** [Dillonb/n64#19]
![image](https://user-images.githubusercontent.com/50224630/121788315-32e4b080-cb81-11eb-9fc2-8a06f6eebd5a.png)
The polygons on the sides of the selection screen are missing/rendered black.

Tested on 2021-06-12 on Linux Mint 20.

**Comment by Dillonb** [comment]
Resolved in fd1d1175e84671b8eb84a5f51cd7a2c5a826e4bc
