### ISSUE TITLE
Speed too fast on higher hz monitors on Windows build.

### ISSUE THREAD

**Issue by retrobenny** [Dillonb/n64#21]
I was curious about this emulator,so I opened Banjo-Tooie which is not listed in the compatibility list and so far it runs fine but the frame rate cap is using my monitor refresh rate (144hz) instead of just locking it to 60hz (or 59.94hz)/50hz meaning I would have to go through a headache to change monitor settings to access 60hz or suffer the UWP and/or DWM frame-drops by not having access to adaptive sync if set to 60hz on the monitor.

It runs great,just faster than it should be running without intervening.
I changed some Nvidia driver settings for it and it works for reducing it to 60fps but it would be nice if I didn't have to do that.

Tested on 9900KF with Nvidia RTX 2060 Super on an Acer 4K 144Hz (via dual Display Port) G-sync monitor.

Banjo-Tooie is playable at the start at least so far.
I guess this is more of a glorified testing of Banjo-Tooie compatibility than an issue since the issue for frame rate can be bypassed by applying certain settings on Nvidia Control Panel.

**Comment by Vaporeon** [comment]
Ah, so this is why it was running 170 FPS for me 😄.

**Comment by Dillonb** [comment]
This has been fixed :tada: 

The emulator now blocks based on the audio stream, not on vsync. This also fixes PAL games running slightly too fast, as a bonus
