### ISSUE TITLE
User's Manual suggests that TLBP succeeds for invalid entries

### ISSUE THREAD

**Issue by KieronJ** [Dillonb/n64#24]
TLBP currently checks for both a matching address and a valid bit through the common `tlb_probe` function.
The VR4300 User's Manual suggests that TLBP will succeed with a matching address, without checking if the entry is marked as valid.

TLB Invalid Exception servicing section under section 6.4.8 TLB Exceptions.
TLBP operation pseudocode under section 16.6 CPU Instructions.

**Comment by Dillonb** [comment]
Fixed, thanks!
