### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by olivieryuyu** [Dillonb/n64#29]
is it possible to explain what is RSP step metris?

The lowest means the less RSP is busy, right?

I am testing the performances of my fast3d custom ucode and see how I should intepret results.

Thanks!

**Comment by Dillonb** [comment]
Hi @olivieryuyu,

Yes, you're right- those metrics track the number of RSP instructions executed per frame. Lower means your code is more efficient :)

You should know that my RSP emulation isn't completely accurate to the hardware, I don't emulate the speedup gained from interleaving SU and VU instructions, for example. The metrics from my emulator should only be used as a guideline, and obviously you should test on real hardware as well.

**Comment by olivieryuyu** [comment]
Ok thanks!
