### ISSUE TITLE
Kirby 64: The Crystal Shards (USA)- Hangs on black screen after HAL logo with TLB miss

### ISSUE THREAD

**Issue by kev4cards** [Dillonb/n64#31]
Allow the game to play out the logo screens and a black screen will occur.
Relevant log entry: TLB miss PC, now at 0000000080000000

Pressing start on the logo screen will get around this issue and will lead to a black screen if you skip the tutorial upon start of a new game.

**Comment by Dillonb** [comment]
Fixed in https://github.com/Dillonb/n64/commit/9d48d5036cd7a0a32e092980bc5c2615b8fb274c
